before_script:
  - psql -c 'create database truppie_test;' -U postgres
  - bundle exec rake db:migrate
language: ruby
rvm:
  - 2.2.3
services:
  - postgresqli
notifications:
  email:
    - laurinha.sette@gmail.com
