version: '3.5'
services:
  server:
    command: ["./docker/scripts/wait-for-it.sh", "db:5432", "-t", "0", "--", "./docker/scripts/run-server.sh"]
    working_dir: /truppie
    build: .
    volumes:
      - type: bind
        source: .
        target: /truppie
    tty: true
    ports:
      - "3000:3000"
  db:
    env_file: .env-db
    image: postgres:9.4.5
