version: '3.5'
services:
  server:
    command: sh -c "sed -i 's/\r//' ./docker/scripts/*.sh && ./docker/scripts/wait-for-it.sh localhost:5432 -t 0 -- ./docker/scripts/run-server.sh"
    working_dir: /truppie
    build: .
    volumes:
      - type: bind
        source: .
        target: /truppie
    tty: true
    network_mode: "host"
  db:
    env_file: .env-db
    image: postgres:9.4.5
    network_mode: "host"
