version: '3.5'
services:
  cucumber:
    command: ["./docker/scripts/wait-for-it.sh", "localhost:5432", "-t", "0", "--", "./docker/scripts/run-test-e2e.sh"]
    working_dir: /truppie
    build: .
    volumes:
      - ".:/truppie"
    environment:
      - DOCKER_SELENIUM_URL=http://localhost:4444/wd/hub
    tty: true
    network_mode: "host"
  db:
    env_file: .env-db
    image: postgres:9.4.5
    network_mode: "host"
  selenium-chrome:
    image: selenium/standalone-chrome:3.11.0-californium
    volumes:
      - "/dev/shm:/dev/shm"
    network_mode: "host"
